language: python
python:
    - "3.5"
    - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
os:
    - linux
sudo: required
cache: pip
before_install:
    - pip install pytest pytest-cov codecov
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
install:
    - pip install -r requirements.txt
    - pip install -e .
script:
    - python3 setup.py test
after_success:
    - codecov
